name: dblend
favicon: null
layout_spectrum: 0.43756
typography_spectrum: 0.80333
title: Integrated Marketing Design and Communications
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000205'
    - '#bed1bb'
    - '#374a51'
    - '#728479'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
